# -*- coding: utf-8 -*-
"""RealEstate invest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RT7kGRUymECH2ZvZHJBrxlWvG56YsExu
"""

"""
Census API Data Pull for Real Estate Demographic Analysis
=========================================================
Pulls ACS 5-year estimates for zip code tabulation areas (ZCTAs)
targeting households aged 25-45 with incomes over $100k.

Requirements:
    pip install requests pandas tqdm

Get your free Census API key at: https://api.census.gov/data/key_signup.html
"""

import os
import time
import requests
import pandas as pd
from tqdm import tqdm

from google.colab import userdata
userdata.get('CENSUS_API_KEY')

# ─── CONFIG ────────────────────────────────────────────────────────────────────

API_KEY = userdata.get("CENSUS_API_KEY")
BASE_URL = "https://api.census.gov/data/{year}/acs/acs5"

# ACS years to pull (skip 2020 — COVID collection issues)
# Latest available 5-year release is 2023 (published Dec 2024)
YEARS = [2019, 2021, 2022, 2023]

# Optional: limit to specific states for faster dev iteration.
# ZCTAs don't nest inside states in Census geography, so we pull all ZCTAs
# nationally and filter by zip prefix afterward. Set to None for full national pull.
#
# Common zip prefixes by state:
#   California: ["9"]          (all 900-961)
#   Texas:      ["75","76","77","78","79"]
#   Florida:    ["32","33","34"]
#   New York:   ["10","11","12","13","14"]
DEV_ZIP_PREFIXES = ["9"]   # California. Set to None for national pull.

OUTPUT_DIR = "data"
os.makedirs(OUTPUT_DIR, exist_ok=True)


# ─── VARIABLE DEFINITIONS ──────────────────────────────────────────────────────
#
# ACS Table Reference:
#   B01003  → Total population
#   B19001  → Household income brackets (annual)
#   B01001  → Sex by age (detailed age breakdown)
#   B25077  → Median home value
#   B25064  → Median gross rent
#   B11001  → Household type
#   B15003  → Educational attainment
#
# Income brackets we want (households earning $100k+):
#   B19001_013E = $100,000 to $124,999
#   B19001_014E = $125,000 to $149,999
#   B19001_015E = $150,000 to $174,999
#   B19001_016E = $175,000 to $199,999
#   B19001_017E = $200,000 or more
#   B19001_001E = Total households (denominator)
#
# Age brackets we want (population 25-44):
#   Male 25-44:   B01001_011E (25-29), B01001_012E (30-34),
#                 B01001_013E (35-39), B01001_014E (40-44)
#   Female 25-44: B01001_035E (25-29), B01001_036E (30-34),
#                 B01001_037E (35-39), B01001_038E (40-44)
#   Total pop:    B01003_001E



# ─── VARIABLE DEFINITIONS ──────────────────────────────────────────────────────
#
# ACS Table Reference:
#   B01003  → Total population
#   B19001  → Household income brackets (annual)
#   B01001  → Sex by age (detailed age breakdown)
#   B25077  → Median home value
#   B25064  → Median gross rent
#   B11001  → Household type
#   B15003  → Educational attainment
#
# Income brackets we want (households earning $100k+):
#   B19001_013E = $100,000 to $124,999
#   B19001_014E = $125,000 to $149,999
#   B19001_015E = $150,000 to $174,999
#   B19001_016E = $175,000 to $199,999
#   B19001_017E = $200,000 or more
#   B19001_001E = Total households (denominator)
#
# Age brackets we want (population 25-44):
#   Male 25-44:   B01001_011E (25-29), B01001_012E (30-34),
#                 B01001_013E (35-39), B01001_014E (40-44)
#   Female 25-44: B01001_035E (25-29), B01001_036E (30-34),
#                 B01001_037E (35-39), B01001_038E (40-44)
#   Total pop:    B01003_001E

VARIABLES = {
    # Population totals
    "B01003_001E": "total_population",

    # Income brackets (households)
    "B19001_001E": "hh_total",
    "B19001_013E": "hh_income_100_124k",
    "B19001_014E": "hh_income_125_149k",
    "B19001_015E": "hh_income_150_174k",
    "B19001_016E": "hh_income_175_199k",
    "B19001_017E": "hh_income_200k_plus",

    # Age: Male 25-44
    "B01001_011E": "male_25_29",
    "B01001_012E": "male_30_34",
    "B01001_013E": "male_35_39",
    "B01001_014E": "male_40_44",

    # Age: Female 25-44
    "B01001_035E": "female_25_29",
    "B01001_036E": "female_30_34",
    "B01001_037E": "female_35_39",
    "B01001_038E": "female_40_44",

    # Housing market context
    "B25077_001E": "median_home_value",
    "B25064_001E": "median_gross_rent",

    # Household count
    "B11001_001E": "total_households",

    # Supply-side housing stock
    "B25001_001E": "total_housing_units",
    "B25003_002E": "owner_occupied_units",
    "B25003_003E": "renter_occupied_units",
}


# ─── FETCH FUNCTIONS ───────────────────────────────────────────────────────────

def build_get_string(variables: dict) -> str:
    """Build the ?get= query string from variable dict."""
    return "NAME," + ",".join(variables.keys())


def fetch_zcta_data(year: int, zip_prefixes: list = None) -> pd.DataFrame:
    """
    Fetch ACS data for ZCTAs in a given year.

    ZCTAs don't nest inside states in Census geography, so we always pull
    the full national ZCTA list and optionally filter by zip prefix afterward.

    Args:
        year: ACS 5-year estimate year (e.g. 2022 = 2018-2022 survey)
        zip_prefixes: list of string prefixes to keep, e.g. ["9"] for CA
                      or ["75","76"] for parts of Texas. None = keep all.
    """
    url = BASE_URL.format(year=year)
    get_str = build_get_string(VARIABLES)

    params = {
        "get": get_str,
        "for": "zip code tabulation area:*",
        "key": API_KEY,
    }

    label = f"[prefixes: {zip_prefixes}]" if zip_prefixes else "[national]"
    print(f"\n→ Fetching {year} ACS data  {label}...")
    resp = requests.get(url, params=params, timeout=120)

    if resp.status_code != 200:
        raise ValueError(
            f"Census API error {resp.status_code} for year {year}:\n{resp.text[:500]}"
        )

    raw = resp.json()
    headers = raw[0]
    rows = raw[1:]

    df = pd.DataFrame(rows, columns=headers)
    df["year"] = year
    df = df.rename(columns={"zip code tabulation area": "zcta"})

    # Filter by zip prefix if requested
    if zip_prefixes:
        mask = df["zcta"].str.startswith(tuple(zip_prefixes))
        df = df[mask].copy()

    # Rename Census variable codes to human-readable names
    df = df.rename(columns=VARIABLES)

    # Keep only relevant columns
    cols_to_keep = ["zcta", "year", "NAME"] + list(VARIABLES.values())
    df = df[[c for c in cols_to_keep if c in df.columns]]

    # Cast numeric columns (Census uses -666666666 as null sentinel)
    for col in VARIABLES.values():
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")
    df = df.replace(-666666666, pd.NA)

    print(f"   ✓ {len(df):,} ZCTAs returned for {year}")
    return df


# ─── DERIVED METRICS ───────────────────────────────────────────────────────────

def compute_derived_metrics(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add computed columns on top of raw Census variables.
    These are the core inputs for the opportunity scoring model.
    """

    # Total population aged 25-44
    age_cols = [
        "male_25_29", "male_30_34", "male_35_39", "male_40_44",
        "female_25_29", "female_30_34", "female_35_39", "female_40_44",
    ]
    df["pop_25_44"] = df[[c for c in age_cols if c in df.columns]].sum(axis=1, skipna=True)

    # % of total population aged 25-44
    df["pct_pop_25_44"] = (df["pop_25_44"] / df["total_population"] * 100).round(2)

    # Total households earning $100k+
    income_100k_cols = [
        "hh_income_100_124k", "hh_income_125_149k", "hh_income_150_174k",
        "hh_income_175_199k", "hh_income_200k_plus",
    ]
    df["hh_income_100k_plus"] = df[[c for c in income_100k_cols if c in df.columns]].sum(axis=1, skipna=True)

    # % of households earning $100k+
    df["pct_hh_income_100k_plus"] = (df["hh_income_100k_plus"] / df["hh_total"] * 100).round(2)

    # Affordability ratio: median income proxy vs home value
    # Lower ratio = more affordability headroom for new construction
    # We use $100k as a rough income proxy since we don't have median income here
    df["home_value_to_income_ratio"] = (df["median_home_value"] / 100000).round(2)

    # Supply-side metrics
    df["pct_owner_occupied"] = (
        df["owner_occupied_units"] / df["total_housing_units"] * 100
    ).round(2)

    # demand_supply_gap: positive = more potential buyers than owner-occupied units
    df["demand_supply_gap"] = (
        df["hh_income_100k_plus"] - df["owner_occupied_units"]
    ).round(0)

    # units_per_target_hh: lower = less supply relative to demand
    df["units_per_target_hh"] = (
        df["total_housing_units"] / df["hh_income_100k_plus"].replace(0, pd.NA)
    ).round(2)

    return df


# ─── CHANGE / TREND CALCULATION ────────────────────────────────────────────────

def compute_trends(df_all_years: pd.DataFrame) -> pd.DataFrame:
    """
    Pivot the multi-year data to compute year-over-year changes
    in key demographic metrics per ZCTA.

    Returns a wide-format DataFrame (one row per ZCTA) with trend columns.
    """
    metrics = [
        "pct_pop_25_44", "pct_hh_income_100k_plus", "total_population",
        "demand_supply_gap", "units_per_target_hh",
    ]
    years = sorted(df_all_years["year"].unique())

    pivot = df_all_years.pivot_table(
        index="zcta",
        columns="year",
        values=metrics,
        aggfunc="first",
    )

    # Flatten column names: e.g. ('pct_pop_25_44', 2019) → 'pct_pop_25_44_2019'
    pivot.columns = [f"{metric}_{year}" for metric, year in pivot.columns]
    pivot = pivot.reset_index()

    # Trend: earliest to most recent year in pull
    year_start = min(years)
    year_end   = max(years)
    suffix     = f"{str(year_start)[2:]}_{str(year_end)[2:]}"

    if year_start in years and year_end in years:
        for metric in metrics:
            col_start = f"{metric}_{year_start}"
            col_end   = f"{metric}_{year_end}"
            if col_start in pivot.columns and col_end in pivot.columns:
                pivot[f"{metric}_change_{suffix}"] = (
                    pivot[col_end] - pivot[col_start]
                ).round(2)
                pivot[f"{metric}_pct_change_{suffix}"] = (
                    (pivot[col_end] - pivot[col_start]) / pivot[col_start] * 100
                ).round(2)

    return pivot


# ─── OPPORTUNITY SCORE ─────────────────────────────────────────────────────────

def compute_opportunity_score(df_wide: pd.DataFrame) -> pd.DataFrame:
    """
    Build a composite opportunity score (0-100) for each ZCTA.

    Scoring dimensions:
        1. Target density (35%)   → pct of high-income 25-44yo households
        2. Growth momentum (25%)  → YoY increase in target demographic
        3. Affordability (25%)    → home value to income headroom
        4. Penetration gap (15%)  → large target pop relative to housing stock
    """

    def normalize(series: pd.Series) -> pd.Series:
        """Min-max normalize a series to 0-100."""
        mn, mx = series.min(), series.max()
        if mx == mn:
            return pd.Series([50.0] * len(series), index=series.index)
        return ((series - mn) / (mx - mn) * 100).round(2)

    df = df_wide.copy()

    def latest_col(prefix):
        """Return most recent column matching prefix, or None."""
        matches = sorted([c for c in df.columns if c.startswith(prefix)], reverse=True)
        return matches[0] if matches else None

    # --- Dimension 1: Target Density ---
    density_col = latest_col("pct_hh_income_100k_plus_2")
    df["score_density"] = normalize(df[density_col].fillna(0)) if density_col else 50.0

    # --- Dimension 2: Growth Momentum ---
    growth_col = latest_col("pct_hh_income_100k_plus_change_")
    df["score_growth"] = normalize(df[growth_col].fillna(0)) if growth_col else 50.0

    # --- Dimension 3: Affordability Headroom ---
    affordability_col = latest_col("home_value_to_income_ratio_2")
    if affordability_col:
        df["score_affordability"] = 100 - normalize(
            df[affordability_col].fillna(df[affordability_col].median())
        )
    else:
        df["score_affordability"] = 50.0

    # --- Dimension 4: Penetration Gap (supply-powered) ---
    # Lower units-per-target-HH = less supply relative to demand = higher opportunity
    supply_col = latest_col("units_per_target_hh")
    if supply_col:
        capped = df[supply_col].clip(upper=df[supply_col].quantile(0.99))
        df["score_penetration"] = 100 - normalize(capped.fillna(capped.median()))
    else:
        fallback = latest_col("pct_pop_25_44_2")
        df["score_penetration"] = normalize(df[fallback].fillna(0)) if fallback else 50.0

    # --- Composite Score ---
    weights = {
        "score_density": 0.35,
        "score_growth": 0.25,
        "score_affordability": 0.25,
        "score_penetration": 0.15,
    }

    df["opportunity_score"] = sum(
        df[col] * weight for col, weight in weights.items()
    ).round(2)

    return df



# ─── TIER LABELS ──────────────────────────────────────────────────────────────────────────

def assign_tiers(df: pd.DataFrame) -> pd.DataFrame:
    """
    Assign each ZCTA to an investment tier with a one-line narrative rationale.

    Tiers (by opportunity_score percentile):
        BUILD NOW   top 15%  -- strong buyer pool + real supply gap today
        WATCH LIST  next 20% -- solid fundamentals with meaningful momentum
        EMERGING    next 25% -- demographic tailwinds, thinner current density
        MONITOR     bottom 40% -- insufficient signal for near-term investment
    """
    df = df.copy()
    df["score_rank_pct"] = df["opportunity_score"].rank(pct=True) * 100

    def _latest(prefix):
        matches = sorted([c for c in df.columns if c.startswith(prefix)], reverse=True)
        return matches[0] if matches else None

    density_col  = _latest("pct_hh_income_100k_plus_2")
    growth_col   = _latest("pct_hh_income_100k_plus_change_")
    supply_col   = _latest("units_per_target_hh")
    hv_col       = _latest("home_value_to_income_ratio_2")

    tiers, rationales = [], []

    for _, row in df.iterrows():
        pct      = row["score_rank_pct"]
        density  = float(row[density_col])  if density_col  and pd.notna(row[density_col])  else 0.0
        growth   = float(row[growth_col])   if growth_col   and pd.notna(row[growth_col])   else 0.0
        supply   = float(row[supply_col])   if supply_col   and pd.notna(row[supply_col])   else 999.0
        hv_ratio = float(row[hv_col])       if hv_col       and pd.notna(row[hv_col])       else 5.0
        zcta     = row["zcta"]

        if pct >= 85:
            tier = "BUILD NOW"
            if density >= 40:
                rationale = (f"ZIP {zcta}: {density:.0f}% high-income households, "
                             f"{supply:.1f} units/target HH -- large pool, tight supply.")
            elif growth >= 10:
                rationale = (f"ZIP {zcta}: target demographic grew {growth:+.1f}pp -- "
                             f"rapid formation + supply gap = first-mover opportunity.")
            else:
                rationale = (f"ZIP {zcta}: top-tier composite across density, momentum, "
                             f"and affordability -- recommend immediate site study.")

        elif pct >= 65:
            tier = "WATCH LIST"
            if growth >= 5:
                rationale = (f"ZIP {zcta}: {growth:+.1f}pp income-demographic growth; "
                             f"monitor supply tightening before land acquisition.")
            elif hv_ratio < 3.5:
                rationale = (f"ZIP {zcta}: home-value/income ratio {hv_ratio:.1f}x leaves "
                             f"pricing headroom -- commit on next positive momentum signal.")
            else:
                rationale = (f"ZIP {zcta}: above-average fundamentals; revisit after "
                             f"next ACS release to confirm sustained trajectory.")

        elif pct >= 40:
            tier = "EMERGING"
            if density < 20 and growth > 0:
                rationale = (f"ZIP {zcta}: modest buyer share ({density:.0f}%) but growing -- "
                             f"early-stage suburban formation, long-horizon play.")
            elif supply < 5:
                rationale = (f"ZIP {zcta}: tight stock ({supply:.1f} units/target HH) signals "
                             f"pent-up demand; buyer density still building.")
            else:
                rationale = (f"ZIP {zcta}: nascent tailwinds -- revisit when income share "
                             f"crosses 25% or supply gap widens further.")

        else:
            tier = "MONITOR"
            rationale = (f"ZIP {zcta}: buyer-pool density and growth insufficient "
                         f"for near-term development investment.")

        tiers.append(tier)
        rationales.append(rationale)

    df["investment_tier"] = tiers
    df["rationale"] = rationales

    order = {"BUILD NOW": 0, "WATCH LIST": 1, "EMERGING": 2, "MONITOR": 3}
    df["_sort"] = df["investment_tier"].map(order)
    df = df.sort_values(["_sort", "opportunity_score"], ascending=[True, False])
    df = df.drop(columns=["_sort", "score_rank_pct"])
    return df


# ─── MAIN ──────────────────────────────────────────────────────────────────────

def main():
    if API_KEY == "YOUR_API_KEY_HERE":
        raise ValueError(
            "Set your Census API key:\n"
            "  export CENSUS_API_KEY=your_key_here\n"
            "Or edit API_KEY at the top of this file.\n"
            "Get a free key at: https://api.census.gov/data/key_signup.html"
        )

    all_years_dfs = []

    for year in YEARS:
        df = fetch_zcta_data(year, zip_prefixes=DEV_ZIP_PREFIXES)
        df = compute_derived_metrics(df)
        all_years_dfs.append(df)
        time.sleep(0.5)  # Be polite to Census servers

    # Save raw long-format data
    df_long = pd.concat(all_years_dfs, ignore_index=True)
    raw_path = os.path.join(OUTPUT_DIR, "acs_raw_long.csv")
    df_long.to_csv(raw_path, index=False)
    print(f"\n✓ Saved raw long-format data → {raw_path}")
    print(f"  Shape: {df_long.shape}")

    # Compute trends (wide format, one row per ZCTA)
    print("\n→ Computing year-over-year trends...")
    df_trends = compute_trends(df_long)

    # Compute opportunity scores
    print("→ Computing opportunity scores...")
    df_scored = compute_opportunity_score(df_trends)

    # Assign investment tiers
    print("\n→ Assigning investment tiers...")
    df_scored = assign_tiers(df_scored)

    # Save scored + tiered output
    scored_path = os.path.join(OUTPUT_DIR, "zcta_scored.csv")
    df_scored.to_csv(scored_path, index=False)
    print(f"\u2713 Saved scored ZCTA data \u2192 {scored_path}")
    print(f"  Shape: {df_scored.shape}")

    # Tier summary
    print("\n" + "=" * 70)
    print("INVESTMENT TIER SUMMARY")
    print("=" * 70)
    for tier in ["BUILD NOW", "WATCH LIST", "EMERGING", "MONITOR"]:
        n = (df_scored["investment_tier"] == tier).sum()
        print(f"  {tier:<12} {n:>4} zip codes")

    for tier in ["BUILD NOW", "WATCH LIST", "EMERGING"]:
        subset = df_scored[df_scored["investment_tier"] == tier].head(10)
        if subset.empty:
            continue
        print(f"\n" + "-" * 70)
        print(f"  {tier}")
        print("-" * 70)
        for _, row in subset.iterrows():
            print(f"  [{row['opportunity_score']:5.1f}]  {row['rationale']}")

    return df_long, df_scored


if __name__ == "__main__":
    df_long, df_scored = main()

# # ─── CONFIG ────────────────────────────────────────────────────────────────────

# API_KEY = userdata.get("CENSUS_API_KEY")
# BASE_URL = "https://api.census.gov/data/{year}/acs/acs5"

# YEARS = [2019, 2024]

# # Optional: limit to specific states for faster dev iteration.
# # ZCTAs don't nest inside states in Census geography, so we pull all ZCTAs
# # nationally and filter by zip prefix afterward. Set to None for full national pull.
# #
# # Common zip prefixes by state:
# #   California: ["9"]          (all 900-961)
# #   Texas:      ["75","76","77","78","79"]
# #   Florida:    ["32","33","34"]
# #   New York:   ["10","11","12","13","14"]
# DEV_ZIP_PREFIXES = ["9"]   # California. Set to None for national pull.

# OUTPUT_DIR = "data"
# os.makedirs(OUTPUT_DIR, exist_ok=True)


# # ─── VARIABLE DEFINITIONS ──────────────────────────────────────────────────────
# #
# # ACS Table Reference:
# #   B01003  → Total population
# #   B19001  → Household income brackets (annual)
# #   B01001  → Sex by age (detailed age breakdown)
# #   B25077  → Median home value
# #   B25064  → Median gross rent
# #   B11001  → Household type
# #   B15003  → Educational attainment
# #
# # Income brackets we want (households earning $100k+):
# #   B19001_013E = $100,000 to $124,999
# #   B19001_014E = $125,000 to $149,999
# #   B19001_015E = $150,000 to $174,999
# #   B19001_016E = $175,000 to $199,999
# #   B19001_017E = $200,000 or more
# #   B19001_001E = Total households (denominator)
# #
# # Age brackets we want (population 25-44):
# #   Male 25-44:   B01001_011E (25-29), B01001_012E (30-34),
# #                 B01001_013E (35-39), B01001_014E (40-44)
# #   Female 25-44: B01001_035E (25-29), B01001_036E (30-34),
# #                 B01001_037E (35-39), B01001_038E (40-44)
# #   Total pop:    B01003_001E

# VARIABLES = {
#     # Population totals
#     "B01003_001E": "total_population",

#     # Income brackets (households)
#     "B19001_001E": "hh_total",
#     "B19001_013E": "hh_income_100_124k",
#     "B19001_014E": "hh_income_125_149k",
#     "B19001_015E": "hh_income_150_174k",
#     "B19001_016E": "hh_income_175_199k",
#     "B19001_017E": "hh_income_200k_plus",

#     # Age: Male 25-44
#     "B01001_011E": "male_25_29",
#     "B01001_012E": "male_30_34",
#     "B01001_013E": "male_35_39",
#     "B01001_014E": "male_40_44",

#     # Age: Female 25-44
#     "B01001_035E": "female_25_29",
#     "B01001_036E": "female_30_34",
#     "B01001_037E": "female_35_39",
#     "B01001_038E": "female_40_44",

#     # Housing market context
#     "B25077_001E": "median_home_value",
#     "B25064_001E": "median_gross_rent",

#     # Household count
#     "B11001_001E": "total_households",
# }

# # ─── FETCH FUNCTIONS ───────────────────────────────────────────────────────────

# def build_get_string(variables: dict) -> str:
#     """Build the ?get= query string from variable dict."""
#     return "NAME," + ",".join(variables.keys())


# def fetch_zcta_data(year: int, state_fips: str = None) -> pd.DataFrame:
#     """
#     Fetch ACS data for all ZCTAs in a given year.

#     If state_fips is provided, fetches only ZCTAs within that state
#     (much faster for development). Set to None for a national pull.
#     """
#     url = BASE_URL.format(year=year)
#     get_str = build_get_string(VARIABLES)

#     if state_fips:
#         # ZCTAs don't nest cleanly inside states in Census geography,
#         # but this filter still works as a bounding approximation.
#         params = {
#             "get": get_str,
#             "for": "zip code tabulation area:*",
#             "in": f"state:{state_fips}",
#             "key": API_KEY,
#         }
#     else:
#         params = {
#             "get": get_str,
#             "for": "zip code tabulation area:*",
#             "key": API_KEY,
#         }

#     print(f"\n→ Fetching {year} ACS data{'  [state: ' + state_fips + ']' if state_fips else ' [national]'}...")
#     resp = requests.get(url, params=params, timeout=60)

#     if resp.status_code != 200:
#         raise ValueError(
#             f"Census API error {resp.status_code} for year {year}:\n{resp.text[:500]}"
#         )

#     raw = resp.json()
#     headers = raw[0]
#     rows = raw[1:]

#     df = pd.DataFrame(rows, columns=headers)
#     df["year"] = year
#     df = df.rename(columns={"zip code tabulation area": "zcta"})

#     # Rename Census variable codes to human-readable names
#     df = df.rename(columns=VARIABLES)

#     # Drop the raw Census code columns that didn't get renamed
#     # (e.g. the 'NAME' column and any extras)
#     cols_to_keep = ["zcta", "year", "NAME"] + list(VARIABLES.values())
#     df = df[[c for c in cols_to_keep if c in df.columns]]

#     # Cast numeric columns
#     numeric_cols = list(VARIABLES.values())
#     for col in numeric_cols:
#         if col in df.columns:
#             df[col] = pd.to_numeric(df[col], errors="coerce")

#     # Census uses -666666666 as a null sentinel
#     df = df.replace(-666666666, pd.NA)

#     print(f"   ✓ {len(df):,} ZCTAs returned for {year}")
#     return df

# # ─── DERIVED METRICS ───────────────────────────────────────────────────────────

# def compute_derived_metrics(df: pd.DataFrame) -> pd.DataFrame:
#     """
#     Add computed columns on top of raw Census variables.
#     These are the core inputs for the opportunity scoring model.
#     """

#     # Total population aged 25-44
#     age_cols = [
#         "male_25_29", "male_30_34", "male_35_39", "male_40_44",
#         "female_25_29", "female_30_34", "female_35_39", "female_40_44",
#     ]
#     df["pop_25_44"] = df[[c for c in age_cols if c in df.columns]].sum(axis=1, skipna=True)

#     # % of total population aged 25-44
#     df["pct_pop_25_44"] = (df["pop_25_44"] / df["total_population"] * 100).round(2)

#     # Total households earning $100k+
#     income_100k_cols = [
#         "hh_income_100_124k", "hh_income_125_149k", "hh_income_150_174k",
#         "hh_income_175_199k", "hh_income_200k_plus",
#     ]
#     df["hh_income_100k_plus"] = df[[c for c in income_100k_cols if c in df.columns]].sum(axis=1, skipna=True)

#     # % of households earning $100k+
#     df["pct_hh_income_100k_plus"] = (df["hh_income_100k_plus"] / df["hh_total"] * 100).round(2)

#     # Affordability ratio: median income proxy vs home value
#     # Lower ratio = more affordability headroom for new construction
#     # We use $100k as a rough income proxy since we don't have median income here
#     df["home_value_to_income_ratio"] = (df["median_home_value"] / 100000).round(2)

#     return df

# # ─── CHANGE / TREND CALCULATION ────────────────────────────────────────────────
# def compute_trends(df_all_years: pd.DataFrame) -> pd.DataFrame:
#     """
#     Pivot the multi-year data to compute year-over-year changes
#     in key demographic metrics per ZCTA.

#     Returns a wide-format DataFrame (one row per ZCTA) with trend columns.
#     """
#     metrics = ["pct_pop_25_44", "pct_hh_income_100k_plus", "total_population"]
#     years = sorted(df_all_years["year"].unique())

#     pivot = df_all_years.pivot_table(
#         index="zcta",
#         columns="year",
#         values=metrics,
#         aggfunc="first",
#     )

#     # Flatten column names: e.g. ('pct_pop_25_44', 2019) → 'pct_pop_25_44_2019'
#     pivot.columns = [f"{metric}_{year}" for metric, year in pivot.columns]
#     pivot = pivot.reset_index()

#     # YoY change: 2019 → 2022 (3-year trend)
#     if 2019 in years and 2022 in years:
#         for metric in metrics:
#             col_start = f"{metric}_2019"
#             col_end = f"{metric}_2022"
#             if col_start in pivot.columns and col_end in pivot.columns:
#                 pivot[f"{metric}_change_19_22"] = (
#                     pivot[col_end] - pivot[col_start]
#                 ).round(2)
#                 pivot[f"{metric}_pct_change_19_22"] = (
#                     (pivot[col_end] - pivot[col_start]) / pivot[col_start] * 100
#                 ).round(2)

#     return pivot

# # ─── OPPORTUNITY SCORE ─────────────────────────────────────────────────────────

# def compute_opportunity_score(df_wide: pd.DataFrame) -> pd.DataFrame:
#     """
#     Build a composite opportunity score (0-100) for each ZCTA.

#     Scoring dimensions:
#         1. Target density (35%)   → pct of high-income 25-44yo households
#         2. Growth momentum (25%)  → YoY increase in target demographic
#         3. Affordability (25%)    → home value to income headroom
#         4. Penetration gap (15%)  → large target pop relative to housing stock
#     """

#     def normalize(series: pd.Series) -> pd.Series:
#         """Min-max normalize a series to 0-100."""
#         mn, mx = series.min(), series.max()
#         if mx == mn:
#             return pd.Series([50.0] * len(series), index=series.index)
#         return ((series - mn) / (mx - mn) * 100).round(2)

#     df = df_wide.copy()

#     # --- Dimension 1: Target Density ---
#     # Use most recent year (2022)
#     if "pct_hh_income_100k_plus_2022" in df.columns:
#         df["score_density"] = normalize(df["pct_hh_income_100k_plus_2022"].fillna(0))
#     else:
#         df["score_density"] = 50.0

#     # --- Dimension 2: Growth Momentum ---
#     # Increase in % of target demographic 2019→2022
#     if "pct_hh_income_100k_plus_change_19_22" in df.columns:
#         df["score_growth"] = normalize(df["pct_hh_income_100k_plus_change_19_22"].fillna(0))
#     else:
#         df["score_growth"] = 50.0

#     # --- Dimension 3: Affordability Headroom ---
#     # LOWER home value to income ratio = BETTER (more room to price new construction)
#     # We invert: score = 100 - normalized(ratio)
#     if "home_value_to_income_ratio_2022" in df.columns:
#         df["score_affordability"] = 100 - normalize(df["home_value_to_income_ratio_2022"].fillna(df["home_value_to_income_ratio_2022"].median()))
#     else:
#         df["score_affordability"] = 50.0

#     # --- Dimension 4: Penetration Gap ---
#     # High target pop density but potentially lower existing owner-occupied stock
#     if "pct_pop_25_44_2022" in df.columns:
#         df["score_penetration"] = normalize(df["pct_pop_25_44_2022"].fillna(0))
#     else:
#         df["score_penetration"] = 50.0

#     # --- Composite Score ---
#     weights = {
#         "score_density": 0.35,
#         "score_growth": 0.25,
#         "score_affordability": 0.25,
#         "score_penetration": 0.15,
#     }

#     df["opportunity_score"] = sum(
#         df[col] * weight for col, weight in weights.items()
#     ).round(2)

#     return df

# # ─── MAIN ──────────────────────────────────────────────────────────────────────

# def main():
#     if API_KEY == "YOUR_API_KEY_HERE":
#         raise ValueError(
#             "Set your Census API key:\n"
#             "  export CENSUS_API_KEY=your_key_here\n"
#             "Or edit API_KEY at the top of this file.\n"
#             "Get a free key at: https://api.census.gov/data/key_signup.html"
#         )

#     all_years_dfs = []

#     for year in YEARS:
#         df = fetch_zcta_data(year, state_fips=DEV_STATE_FIPS)
#         df = compute_derived_metrics(df)
#         all_years_dfs.append(df)
#         time.sleep(0.5)  # Be polite to Census servers

#     # Save raw long-format data
#     df_long = pd.concat(all_years_dfs, ignore_index=True)
#     raw_path = os.path.join(OUTPUT_DIR, "acs_raw_long.csv")
#     df_long.to_csv(raw_path, index=False)
#     print(f"\n✓ Saved raw long-format data → {raw_path}")
#     print(f"  Shape: {df_long.shape}")

#     # Compute trends (wide format, one row per ZCTA)
#     print("\n→ Computing year-over-year trends...")
#     df_trends = compute_trends(df_long)

#     # Compute opportunity scores
#     print("→ Computing opportunity scores...")
#     df_scored = compute_opportunity_score(df_trends)

#     # Sort by opportunity score descending
#     df_scored = df_scored.sort_values("opportunity_score", ascending=False)

#     # Save scored output
#     scored_path = os.path.join(OUTPUT_DIR, "zcta_scored.csv")
#     df_scored.to_csv(scored_path, index=False)
#     print(f"✓ Saved scored ZCTA data → {scored_path}")
#     print(f"  Shape: {df_scored.shape}")

#     # Print top 20
#     print("\n" + "=" * 60)
#     print("TOP 20 ZIP CODES BY OPPORTUNITY SCORE")
#     print("=" * 60)
#     top20_cols = [
#         "zcta", "opportunity_score",
#         "pct_hh_income_100k_plus_2022",
#         "pct_hh_income_100k_plus_change_19_22",
#         "pct_pop_25_44_2022",
#         "home_value_to_income_ratio_2022",
#     ]
#     available_cols = [c for c in top20_cols if c in df_scored.columns]
#     print(df_scored[available_cols].head(20).to_string(index=False))

#     return df_long, df_scored


# if __name__ == "__main__":
#     df_long, df_scored = main()